### ISSUE TITLE
Update PDF.js package

### ISSUE THREAD

**Issue by jnugent** [pkp/pdfJsViewer#57]
Hi Alec,

The current version of the PDF.js package occasionally has some render problems with certain PDFs.  We had a hosted client point out that in one PDF, some of the images in the PDF were rotated 90 degrees, or flipped upside down.  They looked fine when the PDF was downloaded and opened locally.  I upgraded their plugin to use the most recent build here:

https://github.com/mozilla/pdf.js/releases/tag/v2.5.207

And the problem is solved now.   Can we get that included in the plugin package officially, please?

I can provide links to the affected PDF if you'd like to see the problem in action.

Cheers,
Jason

**Comment by asmecher** [comment]
I've added the new release of pdf.js to `omp-stable-3_2_1`, `ojs-stable-3_2_1`, `ops-stable-3_2_1`, and `master` for OMP, OJS, and OMP. It'll be included in the 3.2.1-2 for each app.

Note that a modified version of the pdf.js viewer is included with the Hypothes.is plugin. When that plugin is enabled, the modified pdf.js will be used instead of the default pdf.js viewer. The modified version is maintained by the folks at hypothes.is, and is older than the current release of pdf.js. See https://github.com/hypothesis/pdf.js-hypothes.is for that repo.
